// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey:  "AIzaSyC4r54-sNJ_TUU6OYV4g8jUtnh0If1I80w",
    appId: '1:1080379527756:web:c6be132736552d225c9ae9',
    messagingSenderId: "1080379527756",
    projectId: 'alumniihub',
    authDomain: "alumniihub.firebaseapp.com",
    storageBucket: 'alumniihub.firebasestorage.app',
    measurementId: "G-TSVE4P5GJV",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCFQLHCKJ4UUnR4KgAQDbR5mlWE_61QkM',
    appId: '1:502856201323:android:08bb2df32400a8358c2d2e',
    messagingSenderId: '1080379527756',
    projectId: 'alumniihub',
    storageBucket: 'alumniihub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqkrsOTLphDG6ApmYVnsX1mYc6NWaM9pE',
    appId: '1:1080379527756:ios:e02432eba7cd77f95c9ae9',
    messagingSenderId: '1080379527756',
    projectId: 'alumniihub',
    storageBucket: 'alumniihub.firebasestorage.app',
    iosBundleId: 'com.example.alumniihub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqkrsOTLphDG6ApmYVnsX1mYc6NWaM9pE',
    appId: '1:1080379527756:ios:e02432eba7cd77f95c9ae9',
    messagingSenderId: '1080379527756',
    projectId: 'alumniihub',
    storageBucket: 'alumniihub.firebasestorage.app',
    iosBundleId: 'com.example.alumniihub',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey:  "AIzaSyC4r54-sNJ_TUU6OYV4g8jUtnh0If1I80w",
    appId: '1:1080379527756:web:c6be132736552d225c9ae9',
    messagingSenderId: "1080379527756",
    projectId: 'alumniihub',
    authDomain: "alumniihub.firebaseapp.com",
    storageBucket: 'alumniihub.firebasestorage.app',
    measurementId: "G-TSVE4P5GJV",
  );
}